### ISSUE TITLE
[MVC-1001]  Show Print Option

### ISSUE THREAD

**Issue by rizwanniazigroupdocs** [groupdocs-annotation/GroupDocs.Annotation-for-.NET#33]
Add requested feature show print button in MVC front-end example.

This issue was originally raised via forum thread:
http://www.groupdocs.com/Community/forums/13351/how-to-save-file-with-annotations/showthread.aspx#13351
http://www.groupdocs.com/Community/forums/16365/unable-to-find-showprint-property-in-annotation-16.x.x-version/showthread.aspx#16365

**Comment by bobkovalex** [comment]
This feature is available in new front-end example:
https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-.NET-MVC
