### ISSUE TITLE
[WebForm-001] Unable to get property 'X' of undefined or null reference

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-annotation/GroupDocs.Annotation-for-.NET#48]
This issue was originally raised via forum thread:
http://www.groupdocs.com/Community/forums/thread/18496.aspx

When annotating a document in Chrome and another Browser IE11 is collaborating on the same file, highlighting text to add a comment triggers an null reference error in the other client (IE11).
This happens either way so this is not a browser-issue.
![error](https://user-images.githubusercontent.com/15940608/28020956-a13af89c-659f-11e7-8159-cb6f79b6a8c7.PNG)

**Comment by bobkovalex** [comment]
Please refer to new front-end examples for the fix:
https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-.NET-MVC
https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-.NET-WebForms
https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-Java-Dropwizard
https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-Java-Spring
