### ISSUE TITLE
[ModernFrontEnd-002] : Unhandled exception is thrown while rendering document

### ISSUE THREAD

**Issue by samicheemagroupdocs** [groupdocs-annotation/GroupDocs.Annotation-for-.NET#61]
While rendering documents an unhandled exception is thrown.
 
![exception](https://user-images.githubusercontent.com/29034002/34290459-4193b0c2-e719-11e7-96ef-c0cf02cdbd05.png)

**Comment by samicheemagroupdocs** [comment]
Any update on this issue ?

**Comment by saqibmasood** [comment]
Fixed in 3b68297.
