### ISSUE TITLE
[ModernFrontEnd-003] : Show real name passed from session on comments without reloading the page

### ISSUE THREAD

**Issue by samicheemagroupdocs** [groupdocs-annotation/GroupDocs.Annotation-for-.NET#65]
When we added comments, on the right pan of the UI it shows Anonymous/Guest on comments. Please show real name on them passed from session, without reloading the page.

**Comment by vitaliy-rezchikov** [comment]
This ticket not actual anymore we have no functionality regarding users on latest GroupDocs.Annotation API
