### ISSUE TITLE
[ModernFrontEnd-004]  : Add Zoom In and Zoom Out option for the documents

### ISSUE THREAD

**Issue by samicheemagroupdocs** [groupdocs-annotation/GroupDocs.Annotation-for-.NET#67]
This issue was originally raised via forum thread:
https://forum.groupdocs.com/t/horizontal-scroll-bar-not-showing-up-when-zoom/5762/5

A new feature is requested. Please add Zoom In and Zoom Out feature for the documents. Thanks

**Comment by bobkovalex** [comment]
@samicheemagroupdocs this feature has been added to our new front-end examples.
Please close this issue if it is obsolete.

Thanks.
