### ISSUE TITLE
[ModernFrontEnd-005] : Implementing the feature for customizing the collaborator privileges.

### ISSUE THREAD

**Issue by aleksandarvidakovicaspose** [groupdocs-annotation/GroupDocs.Annotation-for-.NET#77]
Hi,
Please notice that isn't possible to forbid add/update/delete annotation replies regardless of the collaborator privileges. The same scenario occurs in the Modern Front End showcase.
Please investigate.
Thanks.

**Comment by vitaliy-rezchikov** [comment]
The issue not actual anymore because GroupDocs.Annotation API have no collaboration functionality
