### ISSUE TITLE
GroupDocs Annotation integration in React/Angular

### ISSUE THREAD

**Issue by kmehmoodkhan** [groupdocs-annotation/GroupDocs.Annotation-for-.NET#94]
Hi, We are intending to integrate GroupDocs annotation tool in a React based project. But we also need to do some customization like if we have to hide a file upload tab etc, then is it possible to do so?

Will highly appreciate it if someone can help.

**Comment by bobkovalex** [comment]
Hi @kmehmoodkhan 

Thanks for asking.
In our Angular Based UI sample app it is possible.
Simply set `upload` parameter to `false` in the [configuration](https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-.NET-MVC/blob/master/src/configuration.yml#L37) file.

Best Regards

**Comment by kmehmoodkhan** [comment]
Thanks, Bob for the reply. I am interested in React based development, can you please guide how to integrate this product in React based application? 

Best regards,

Kausar

**Comment by bobkovalex** [comment]
@kmehmoodkhan 

Running Angular based app in React is a bit tricky, see if following [article](https://medium.embengineering.com/micro-front-end-and-web-components-ce6ae87c3b7f) helps.

Another option is to use our jQuery based GroupDocs.Annotation but it is outdated and won't get any updates.

Please note, at the moment we do not have any ETA on supporting React natively.

Best Regards
